### ISSUE TITLE
Looking for sponsorship for swimmingwatchtools.com

### ISSUE THREAD

**Issue by miklcct** [PeterK-end/swim-data-analyser#3]
I am looking for this project to be the planned modernisation of [Swimming Watch Tools](https://swimmingwatchtools.com/), which I am the current maintainer.

In order for this to happen, I would need that:

- this can load, edit, and export swimming .FIT files from my Garmin watch offline.
- this is installable as a Progressive Web App

Also, the email address listed on the website does not work.

**Comment by PeterK-end** [comment]
Hi milkcct,

Thanks for reaching out! I saw your info box on Swimming Watch Tools but began working on something similar because I didn’t see any activity in the past year.

- On exporting .FIT files: To export swimming .FIT files, we would need to integrate parts of the FIT SDK (at least to my knowledge). I believe this is doable, but it’s not high on my priority list. If someone is interested in contributing, we could definitely discuss the implications.

- On PWA: I’m neither a web developer nor a full-time programmer, so I’m not entirely sure what would be required for the app to be considered a "Progressive Web App." Currently, the app consists mainly of JavaScript, HTML, and CSS, so perhaps it's possible? Since the app is still in its early stages, I’d be open to considering it if you could share some insights on what would be needed to make this happen.

Email address typo: You were right—there was a misspelling in the email address. I’ve fixed it in e4aa426456ace92463d5b7514ffaac85fad3ada9.

**Comment by miklcct** [comment]
A progressive web app is a website which satisfies certain requirements, so that it can be "installed" like an app and run without the browser chrome. 

My portfolio has a web app which you can reference: https://github.com/miklcct/WhatFxxxWords

**Comment by PeterK-end** [comment]
Sounds good. I will consider it.
